# Generated by Django 6.0 on 2026-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_discussion_group_chat_link_handle_chat_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('group', 'Группа'), ('channel', 'Канал'), ('direct', 'Личная переписка')], default='group', max_length=10),
        ),
    ]
