# Generated by Django 5.1.4 on 2026-01-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_in_chats', to='chats.message'),
        ),
    ]
