# Generated by Django 6.0 on 2026-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_2fa_enable_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_2fa_enable',
            new_name='is_2fa_enabled',
        ),
    ]
