# Generated by Django 6.0 on 2026-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_2fa_enable_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_handle',
            field=models.CharField(db_index=True, default='', help_text='Если оставить пустым, сгенерируется автоматически', max_length=32, unique=True, verbose_name='Тэг (username как в TG)'),
            preserve_default=False,
        ),
    ]
