# Generated by Django 6.0 on 2026-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_handle',
            field=models.CharField(blank=True, db_index=True, help_text='Если оставить пустым, сгенерируется автоматически', max_length=32, unique=True, verbose_name='Тэг (username как в TG)'),
        ),
    ]
